version: 1

update_configs:
  - package_manager: javascript
    directory: '/'
    update_schedule: weekly
    default_reviewers:
      - adamelliotfields
    default_labels:
      - dependabot

allowed_updates:
  - match:
      update_type: all
      dependency_type: direct
  - match:
      update_type: security
      dependency_type: indirect

automerged_updates: []

default_assignees: []

ignored_updates: []

target_branch: master

version_requirement_updates: auto
